// <auto-generated />
namespace Bbing.EF.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddRe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRe));
        
        string IMigrationMetadata.Id
        {
            get { return "201807240354157_AddRe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
