// <autogenerated>
//   This file was generated by T4 code generator Bbing_Template.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Bbing.Domain.Model;

namespace Bbing.Domain.IRepositories
{
	public partial interface IUsersRepository : IRepository<Users>
	{

	}
}
